name: C/C++ CI with Make (Arch Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: pacman -Syu --noconfirm base-devel

    - name: Build with Make
      run: make